<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.teachersfcu</groupId>
	<artifactId>accounts-api</artifactId>
	<version>1.19.0</version>
	<packaging>mule-application</packaging>

	<name>accounts-api</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<app.runtime>4.6-java17</app.runtime>
		<mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>
		<munit.version>3.2.1</munit.version>
		<munit.required.coverage>75</munit.required.coverage>
		<http.connector.version>1.10.3</http.connector.version>
		<email.connector.version>1.7.4</email.connector.version>
		<mssql.connector.version>11.2.3.jre17</mssql.connector.version>
		<db.connector.version>1.14.13</db.connector.version>
		<socket.connector.version>1.2.5</socket.connector.version>
		<apikit.module.version>1.11.1</apikit.module.version>
		<secure.property.version>1.2.7</secure.property.version>
		<wsc.connector.version>1.10.3</wsc.connector.version>
		<objectstore.connector.version>1.2.2</objectstore.connector.version>
		<anypoint.platform.config.analytics.agent.enabled>true</anypoint.platform.config.analytics.agent.enabled>
		<fiserv.authentication.connector.version>1.0.3-SNAPSHOT</fiserv.authentication.connector.version>
		<cloudhub.application.name>accounts-sys-api-${mule.env}-v1</cloudhub.application.name>
		<cloudhub.businessGroupId>4a5248bb-d9bc-4dbe-b4f6-8fb73e261dd4</cloudhub.businessGroupId>
		<cloudhub.deployment.region>us-east-1</cloudhub.deployment.region>
		<cloudhub.deployment.workerType>SMALL</cloudhub.deployment.workerType>
		<cloudhub.deployment.workers>2</cloudhub.deployment.workers>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<cloudHubDeployment>
						<uri>https://anypoint.mulesoft.com</uri>
						<muleVersion>${app.runtime}</muleVersion>
						<username>${username}</username>
						<password>${password}</password>
						<applicationName>${cloudhub.application.name}</applicationName>
						<environment>${environment}</environment>
						<businessGroupId>${cloudhub.businessGroupId}</businessGroupId>
						<objectStoreV2>true</objectStoreV2>
						<properties>
							<mule.env>${mule.env}</mule.env>
							<mule.key>${mule.key}</mule.key>
							<anypoint.platform.client_id>${anypoint.platform.client_id}</anypoint.platform.client_id>
							<anypoint.platform.client_secret>${anypoint.platform.client_secret}</anypoint.platform.client_secret>
							<anypoint.platform.config.analytics.agent.enabled>${anypoint.platform.config.analytics.agent.enabled}</anypoint.platform.config.analytics.agent.enabled>
							<anypoint.platform.visualizer.tags>${anypoint.platform.visualizer.tags}</anypoint.platform.visualizer.tags>
							<anypoint.platform.visualizer.layer>${anypoint.platform.visualizer.layer}</anypoint.platform.visualizer.layer>
						</properties>
						<region>${cloudhub.deployment.region}</region>
						<workerType>${cloudhub.deployment.workerType}</workerType>
						<workers>${cloudhub.deployment.workers}</workers>
					</cloudHubDeployment>
					<classifier>mule-application</classifier>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>com.oracle.database.jdbc</groupId>
							<artifactId>ojdbc11</artifactId>
						</sharedLibrary>
						<sharedLibrary>
							<groupId>com.microsoft.sqlserver</groupId>
							<artifactId>mssql-jdbc</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
				<version>${munit.version}</version>
				<executions>
					<execution>
						<id>test</id>
						<phase>test</phase>
						<goals>
							<goal>test</goal>
							<goal>coverage-report</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<coverage>
						<runCoverage>true</runCoverage>
						<failBuild>false</failBuild>
						<requiredApplicationCoverage>${munit.required.coverage}</requiredApplicationCoverage>
						<ignoreFlows>
							<ignoreFlow>determine-status-code</ignoreFlow>
							<ignoreFlow>determine-status-code-multiple-responses</ignoreFlow>
							<ignoreFlow>post:\accounts\(account-number)\link-statement-account:application\json:apiConfig</ignoreFlow>
							<ignoreFlow>post:\accounts\(account-number)\roles:application\json:apiConfig</ignoreFlow>
							<ignoreFlow>account-role-maintenance</ignoreFlow>
							<ignoreFlow>account-statement-linking</ignoreFlow>
							<ignoreFlow>post:\accounts\(account-number)\link-draw-account:application\json:apiConfig</ignoreFlow>
							<ignoreFlow>courtesy-opt-in</ignoreFlow>
						</ignoreFlows>
						<formats>
							<format>html</format>
							<format>console</format>
						</formats>
					</coverage>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>${http.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<version>2.9.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc11</artifactId>
			<version>23.6.0.24.10</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>${mssql.connector.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>${apikit.module.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<version>${socket.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-objectstore-connector</artifactId>
			<version>${objectstore.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-wsc-connector</artifactId>
			<version>${wsc.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<version>${secure.property.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-email-connector</artifactId>
			<version>${email.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-db-connector</artifactId>
			<version>${db.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>${munit.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>${munit.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>4a5248bb-d9bc-4dbe-b4f6-8fb73e261dd4</groupId>
			<artifactId>fiserv-authentication</artifactId>
			<version>${fiserv.authentication.connector.version}</version>
			<classifier>mule-plugin</classifier>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>anypoint-exchange-v2</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v2/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange V3</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>mulesoft release repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

</project>
