api:
  id: "16452999"
  
tls.keystore:
  type: "PKCS12"
  path: "cert/accounts-api-dev.p12"
  alias: "tfcu"
  
tls.truststore:
  type: "PKCS12"
  path: "cert/fiserv-trust-store-dev.p12"
  
httpRequester:
  host: "tfcu-preproduction-dlb.lb.anypointdns.net"
  port: "443"
  path: "/api/*"
  connectionIdleTimeoutMilliseconds: "90000"
  responseTimeoutMilliseconds: "90000"
  
db:
  oracle:
    host: "hq-oracle-test.teachersfcu.org"
    port: "1521"
    instance: "test"
    url: "jdbc:oracle:thin:@${db.oracle.host}:${db.oracle.port}/${db.oracle.instance}"
    user: "JAPI"
    connectionWaitTimeout: "0"
    initialPoolSize: "5"
    maxPoolSize: "50"
    minPoolSize: "10"
    timeToLiveConnectionTimeout: "18000"
    validateConnectionOnBorrow: "true"
  pooling:
    acquire:
      increment: "5"
    cache:
      size: "5"
  mssql:
    host: "10.0.102.70"
    port: ""
    instance: "coreDB"
    user: "JAPI"
    databaseName: "MulesoftBatch"      

  
fiserv:
  safProdInteg:
    applicationId: "7e837e75-2e19-45d5-8c3a-4735a275a6cf"
    networkNodeName: "FULL"
    cacheTTLInHours: "8"
    wsdlPath: "wsdl/safProductIntegration.wsdl"
    address: "https://saf-dev.teachersfcu.org:20001/SAF/ProductIntegration/ProductIntegration.asmx"
    timeoutInMilliseconds: "60000"
  
  dnaService:
    wsdlPath: "wsdl/CoreApiService_1.wsdl"
    address: "https://saf-dev.teachersfcu.org:20001/Extensions/DNA.CoreApiService/CoreApiService.svc/Soap11"
    timeoutInMilliseconds: "60000"

email:
    addressesEmailNotifications: "revanth.balaraju@teachersfcu.org,Roopa.Suryanarayana@teachersfcu.org,sadhana.chalapathy@teachersfcu.org,sairam.gudimettla@teachersfcu.org,raghavendra.rajendra@teachersfcu.org,jeevan.kannan@teachersfcu.org,dao_development@teachersfcu.org"
#    addressesEmailNotifications: "revanth.balaraju@teachersfcu.org"
    userName: "send_coreapps@teachersfcu.org"

Failureschedular: "0 59 23 ? * 1-7"
schedularInterval: "0 */30 * ? * 1-7"
achRetryInterval: "30000"

drawAccountsRetryInterval: "2000"
drawAccountsRetriesNumber: "1"

notification:
   path: "/test/notification/v1/error/notification"
   retryCount: "5"
   retryInterval: "3000"
 