#%RAML 1.0 DataType

displayName: ACH Transfer Response
description: Create ACH transfer response structure
type: object
properties:
  requestNumber?: integer
  requestTypeCode: integer
  wasSuccessful: boolean
  allotmentResponses:
    type: object
    properties:
      fromAccountNumber: string
      fromRtxnNbr: string
      toAccountNumber: string
      toRtxnNbr: string
      transactionAmount: number
      transactionDate: string
      transactionReferenceNbr: string
      transferValue: string
  errors?: 
    type: array
    items:
      type: !include error.raml
  userAuthentication: !include user-authentication.raml

examples:
  achTransferResponse: !include ../examples/ach-transfer-response-example.raml



