#%RAML 1.0 DataType

displayName: Error
description: Member Lookup Error Information
type: object
properties:
  errorMessage: string
  errorNumber: string
  oraErrorMessage: string
  rtxnExceptionMessage: string
  rtxnExceptionNumber: string