#%RAML 1.0 DataType

displayName: Get CD Interest Rates Response
description: Get CD Interest Rates Response
type: object
properties:
  channel?: string
  zip?: string
  major?: string
  minor?: string
  minorDescription?: string
  state?: string
  regionOrgNumber?: string
  region?: string
  branchOrgNumber?: string
  branch?: string
  calcSched?: string
  calcSchedName?: string
  tier?: string
  beginBalance?: string
  endBalance?: string
  rate?: string
  effDate?: string
  inactiveDate?: string
  myRank?: string
 