#%RAML 1.0 DataType

displayName: Create Warning Response
description: Create Warning Response
type: object
properties:
  requestNumber?: integer
  requestTypeCode: integer
  wasSuccessful: boolean
  accountWarnings?:
    type: array
    items:
      type: object
      properties:
        accountNumber?: integer
        effectiveDate?: string
        inactiveDate?: string
        noteNumber?: string
        warningFlagCode?: string
        warningFlagDescription?: string
  errors?: 
    type: array
    items:
      type: !include error.raml
  userAuthentication: !include user-authentication.raml