#%RAML 1.0 DataType

displayName: Create Warning Response
description: Create Warning Response
type: object
properties:
  monetaryTransactionResponse: 
    type: array
    items:
      type: object
      properties:
        requestNumber: integer
        requestTypeCode: integer
        wasSuccessful: boolean
        accountNumber: integer
        cashBoxNumber: string
        cashBoxTransactionNumber: string
        creditedInterestAmount: string
        currentRtxnStatusCode: string
        newAvailable: string
        newLedgerBalance: string
        priorAvailableBalance: string
        rtxnNumber: string
        checkIssues: 
          type: array
          items:
            type: object
            properties:
              checkNumber: string
              status: string
        errors?: 
          type: array
          items:
            type: !include error.raml
  userAuthentication: !include user-authentication.raml