#%RAML 1.0 NamedExample

{
    "allotNbr": "456765326",
    "achRecvAcctTypCd": "SAV",
    "achRecvTypCd": "PERS",    
    "balCatCd": "NOTE",
    "balTypCd": "BAL",
  	"rtxnTypCd": "XDEP",
    "allotTypCd": "ONCE",    
    "effDate": "2023-08-31",
    "initialDueDate": "2023-09-06",
  	"endDate": "2023-09-09",
    "fixedAmt": 12.00,
    "achOrigYN": "Y",    
    "ACHSameDaySettlementYN": "N",
    "extAcctName": "Dave Simpson",
    "recvRouteNbr": "011401533",    
    "extAcctNbr": "1111222233331",
    "addlDesc": "MMD9TFZ",
    "toAccountNumber":"6006785894"
}