#%RAML 1.0 NamedExample

  requestNumber: 12345
  requestTypeCode: 12345
  personNumber: 123456
  wasSuccessful: true
  accountNumber: 5282090
  majorTypeCode: SAV
  minorTypeCode: PSHR
  userAuthentication:
    errors: ""
    wasSuccessful: true