#%RAML 1.0 NamedExample

  requestNumber: 12345
  requestTypeCode: 12345
  wasSuccessful: true
  transferResponse:
    fromAccountNumber: "12610002394965"
    fromRtxnNbr: "5298"
    toAccountNumber: "6006785331"
    toRtxnNbr: "2500"
    transactionAmount: 10
    transactionDate: "2020-05-22T00:00:00"
    transactionReferenceNbr: "6006785331-2500"
    transferValue: "6006785331-2500  22-MAY-20  10"
  userAuthentication:
    errors: ""
    wasSuccessful: true