%dw 2.0
output application/json
import * from dw::core::Strings
ns fs http://www.opensolutions.com/CoreApi
ns ms http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages
ns cm http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages.Common
ns open http://www.opensolutions.com/CoreApi

var messagePayload = message.payload.body.open#SubmitRequestResponse.open#SubmitRequestResult
---
{
	('requestNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RequestNumber as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RequestNumber != null),
	('requestTypeCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RequestTypeCode as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RequestTypeCode?),
	('personNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PersonNumber as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PersonNumber != null),
	'wasSuccessful': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#WasSuccessful as Boolean,
	('accountClassDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountClassDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountClassDescription != null),
	('accountCollateralAccounts': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountCollateralAccounts) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountCollateralAccounts != null),
	('accountCurrencyCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountCurrencyCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountCurrencyCode != null),
	('accountExternalOrganizationIds': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountExternalOrganizationIds) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountExternalOrganizationIds != null),
	('accountLoanLimitHistoryRecords': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountLoanLimitHistoryRecords) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountLoanLimitHistoryRecords != null),
	('accountMaturityDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountMaturityDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountMaturityDate != null),
	('accountNickName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountNickName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountNickName != null),
	('accountNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AccountNumber != null),
	('amountDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AmountDue as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AmountDue != null),
	('amountToPayCurrent': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AmountToPayCurrent as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AmountToPayCurrent != null),
	('availableBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableBalance != null),
	('availableCredit': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableCredit as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableCredit != null),
	('availableToDraw': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableToDraw as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#AvailableToDraw != null),
	('billingLeadDaysOverride': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BillingLeadDaysOverride) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BillingLeadDaysOverride != null),
	('borrowerAvailable': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BorrowerAvailable) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BorrowerAvailable != null),
	('branchOrganizationName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BranchOrganizationName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BranchOrganizationName != null),
	('branchOrganizationNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BranchOrganizationNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#BranchOrganizationNumber != null),
	('cardHoldAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CardHoldAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CardHoldAmount != null),
	('checkHoldAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CheckHoldAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CheckHoldAmount != null),
	('classNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ClassNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ClassNumber != null),
	('closeReasonCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CloseReasonCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CloseReasonCode != null),
	('closeReasonCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CloseReasonCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CloseReasonCodeDescription != null),
	('statementAcount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CombinedStatement.PrimaryStatementAccount) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CombinedStatement.PrimaryStatementAccount != null),
	('contractDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ContractDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ContractDate != null),
	('creditLimit': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CreditLimit as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CreditLimit != null),
	('currentAccountStatusCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentAccountStatusCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentAccountStatusCode != null),
	('currentAccountStatusDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentAccountStatusDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentAccountStatusDescription != null),
	('currentBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentBalance != null),
	('currentTerm': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentTerm) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentTerm != null),
	('currentYearInterestPaid': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentYearInterestPaid as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#CurrentYearInterestPaid != null),
	('deliveryMethodCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DeliveryMethodCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DeliveryMethodCode != null),
	('deliveryMethodCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DeliveryMethodCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DeliveryMethodCodeDescription != null),
	('dueDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DueDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#DueDate != null),
	('escrowBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#EscrowBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#EscrowBalance != null),
	('escrowCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#EscrowCurrentlyDue) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#EscrowCurrentlyDue != null),
	('externalAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAmount != null),
	('externalAmountEffectiveDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAmountEffectiveDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAmountEffectiveDate != null),
	('externalAnnualCost': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAnnualCost as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalAnnualCost != null),
	('externalEntityId': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalEntityId) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalEntityId != null),
	('externalEntityOrganizationNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalEntityOrganizationNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalEntityOrganizationNumber != null),
	('externalInterestRate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalInterestRate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalInterestRate != null),
	('externalOrganizationName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalOrganizationName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ExternalOrganizationName != null),
	('feesCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#FeesCurrentlyDue as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#FeesCurrentlyDue != null),
	('forbearanceBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ForbearanceBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ForbearanceBalance != null),
	('hsaEvents': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#HSAEvents) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#HSAEvents != null),
	('interestAccountCycleCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestAccountCycleCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestAccountCycleCode != null),
	('interestAccountCycleCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestAccountCycleCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestAccountCycleCodeDescription != null),
	('interestBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestBalance) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestBalance != null),
	('interestCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestCurrentlyDue as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestCurrentlyDue != null),
	('interestDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestDate != null),
	('interestPaidToDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestPaidToDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestPaidToDate != null),
	('interestRate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestRate as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestRate != null),
	('interestYield': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestYield) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#InterestYield != null),
	('isChecks': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsChecks as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsChecks != null),
	('isExternalEntity': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsExternalEntity as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsExternalEntity != null),
	('isFamily': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsFamily as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsFamily != null),
	('isImminentDefault': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsImminentDefault as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsImminentDefault != null),
	('isLoanLimit': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsLoanLimit as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsLoanLimit != null),
	('isNewAccountClass': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsNewAccountClass as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsNewAccountClass != null),
	('isPassbook': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsPassbook as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsPassbook != null),
	('isPrinSurplusProc': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsPrinSurplusProc as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsPrinSurplusProc != null),
	('isRestriction': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRestriction as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRestriction != null),
	('isRestrictionExists': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRestrictionExists as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRestrictionExists != null),
	('isRetirement': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRetirement as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRetirement != null),
	('isRevolvingLoan': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRevolvingLoan as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsRevolvingLoan != null),
	('isTransactionAccount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsTransactionAccount as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsTransactionAccount != null),
	('isValid': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsValid as Boolean) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#IsValid != null),
	('lastContactDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastContactDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastContactDate != null),
	('lastDepositDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastDepositDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastDepositDate != null),
	('lastInterestCreditAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestCreditAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestCreditAmount != null),
	('lastInterestCreditDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestCreditDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestCreditDate != null),
	('lastInterestRateChangeDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestRateChangeDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastInterestRateChangeDate != null),
	('lastPaymentAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastPaymentAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastPaymentAmount != null),
	('lastPaymentDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastPaymentDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastPaymentDate != null),
	('lastRenewalDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastRenewalDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastRenewalDate != null),
	('lastStatementDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastStatementDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LastStatementDate != null),
	('lateChargesCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LateChargesCurrentlyDue) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LateChargesCurrentlyDue != null),
	('loanBranchOrganizationNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanBranchOrganizationNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanBranchOrganizationNumber != null),
	('loanInterestRate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanInterestRate as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanInterestRate != null),
	('loanMaturityDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanMaturityDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanMaturityDate != null),
	('loanNickName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanNickName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#LoanNickName != null),
	('mLAggregateBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MLAggregateBalance) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MLAggregateBalance != null),
	('majorAccountTypeCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MajorAccountTypeCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MajorAccountTypeCode != null),
	('managementHoldAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ManagementHoldAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ManagementHoldAmount != null),
	('maturityAnticipatedPayoffDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MaturityAnticipatedPayoffDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MaturityAnticipatedPayoffDate != null),
	('minorAccountTypeCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MinorAccountTypeCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MinorAccountTypeCode != null),
	('minorCustomerDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MinorCustomerDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#MinorCustomerDescription != null),
	('nsfToleranceAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NSFToleranceAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NSFToleranceAmount != null),
	('netLoanInProcessBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NetLoanInProcessBalance) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NetLoanInProcessBalance != null),
	('nextPaymentDueDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NextPaymentDueDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#NextPaymentDueDate != null),
	('openDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OpenDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OpenDate != null),
	('operatingFundAccruedInt': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundAccruedInt) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundAccruedInt != null),
	('operatingFundBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundBalance != null),
	('operatingFundIntRate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundIntRate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OperatingFundIntRate != null),
	('originalLoanAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OriginalLoanAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OriginalLoanAmount != null),
	('orignalLTVRatio': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OrignalLTVRatio) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OrignalLTVRatio != null),
	('ownershipCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OwnershipCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OwnershipCode != null),
	('ownershipCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OwnershipCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#OwnershipCodeDescription != null),
	('paymentMethodCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PaymentMethodCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PaymentMethodCode != null),
	('paymentStatus': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PaymentStatus) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PaymentStatus != null),
	('payoffBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PayoffBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PayoffBalance != null),
	('payoffBalanceAsOfDate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PayoffBalanceAsOfDate) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PayoffBalanceAsOfDate != null),
	('personOrganizationUserFields': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PersonOrganizationUserFields) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PersonOrganizationUserFields != null),
	('pmtCalPeriods': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PmtCalPeriods) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PmtCalPeriods != null),
	('principalBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PrincipalBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PrincipalBalance != null),
	('principalCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PrincipalCurrentlyDue as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PrincipalCurrentlyDue != null),
	('priorInterestRate': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PriorInterestRate as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PriorInterestRate != null),
	('priorYearInterestPaid': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PriorYearInterestPaid as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PriorYearInterestPaid != null),
	('productFullName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ProductFullName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ProductFullName != null),
	('productName': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ProductName) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ProductName != null),
	('regD3Count': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#'RegD3Count') if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#'RegD3Count' != null),
	('regD6Count': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#'RegD6Count') if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#'RegD6Count' != null),
	('regDDAvailableBalance': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegDDAvailableBalance as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegDDAvailableBalance != null),
	('regEODOptional': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegEODOptional) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegEODOptional != null),
	('regularPaymentAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegularPaymentAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RegularPaymentAmount != null),
	('retirementAccountNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementAccountNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementAccountNumber != null),
	('retirementPlanCategory': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementPlanCategory) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementPlanCategory != null),
	('retirementPlanType': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementPlanType) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#RetirementPlanType != null),
	('shareCurrentYearInterestPaid': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ShareCurrentYearInterestPaid) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#ShareCurrentYearInterestPaid != null),
	('sharePriorYearInterestPaid': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SharePriorYearInterestPaid) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SharePriorYearInterestPaid != null),
	('signerFullname': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SignerFullname) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SignerFullname != null),
	('signerPersonNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SignerPersonNumber as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SignerPersonNumber != null),
	('sourceCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SourceCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SourceCode != null),
	('sourceCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SourceCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#SourceCodeDescription != null),
	('statementAccountCycleCode': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#StatementAccountCycleCode) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#StatementAccountCycleCode != null),
	('statementAccountCycleCodeDescription': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#StatementAccountCycleCodeDescription) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#StatementAccountCycleCodeDescription != null),
	('taxOrganizationNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxOrganizationNumber) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxOrganizationNumber != null),
	('taxOwnerFullname': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxOwnerFullname) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxOwnerFullname != null),
	('taxPersonNumber': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxPersonNumber as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TaxPersonNumber != null),
	('totalAmountCurrentlyDue': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TotalAmountCurrentlyDue as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TotalAmountCurrentlyDue != null),
	('totalPerDiem': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TotalPerDiem as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#TotalPerDiem != null),
	('ucfToleranceAmount': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#UCFToleranceAmount as Number) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#UCFToleranceAmount != null),
	'roles': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#Roles.*cm#RoleDetail map {
			('canTransact': $.CanTransact as Boolean) if($.CanTransact != null),
			('entityName': $.EntityName) if($.EntityName != null),
			('entityNumber': $.EntityNumber) if($.EntityNumber != null),
			('entityTypeCode': $.EntityTypeCode) if($.EntityTypeCode != null),
			('isEmployeeRole': $.IsEmployeeRole as Boolean) if($.IsEmployeeRole != null),
			('roleCode': $.RoleCode) if($.RoleCode != null),
			('roleDescription': $.RoleDescription) if($.RoleDescription != null)
	},
	'balances': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#Balances.*ms#Balance map {
		('accuredInterest': $.AccuredInterest as Number) if($.AccuredInterest != null),
		('availableAmount': $.AvailableAmount as Number) if($.AvailableAmount != null),
		('balanceAmount': $.BalanceAmount as Number) if($.BalanceAmount != null),
		('balanceCategoryCode': $.BalanceCategoryCode) if($.BalanceCategoryCode != null),
		('balanceTypeCode': $.BalanceTypeCode) if($.BalanceTypeCode != null),
		('cardHold': $.CardHold as Number) if($.CardHold != null),
		('checkHold': $.CheckHold as Number) if($.CheckHold != null),
		('collectedMonthToDateAverage': $.CollectedMonthToDateAverage as Number) if($.CollectedMonthToDateAverage != null),
		('collectedYearToDateAverage': $.CollectedYearToDateAverage as Number) if($.CollectedYearToDateAverage != null),
		('managementHold': $.ManagementHold as Number) if($.ManagementHold != null),
		('monthToDateAverage': $.MonthToDateAverage as Number) if($.MonthToDateAverage != null),
		('participantAgreementNumber': $.ParticipantAgreementNumber) if($.ParticipantAgreementNumber != null),
		('yearToDateAverage': $.YearToDateAverage as Number) if($.YearToDateAverage != null)
	},
	'userFields': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#PersonOrganizationUserFields.*cm#PersOrgUserField map {
                ('code': $.UserFieldCode) if($.UserFieldCode != null),
                ('description': $.UserFieldDescription) if($.UserFieldDescription != null),
                ('valueDescription': $.UserFieldValueDescription) if($.UserFieldValueDescription != null),
                ('value': $.Value) if($.Value != null)
    },
	('errors': messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#Errors.*fs#Error map ((item, index) -> {
    		'errorMessage': item.ErrorMessage,
    		'errorNumber': item.ErrorNumber as Number,
    		'oraErrorMessage': item.OraErrorMessage,
    		('rtxnExceptionMessage': item.RtxnExceptionMessage) if(item.RtxnExceptionMessage != null),
    		('rtxnExceptionNumber': item.RtxnExceptionNumber) if(item.RtxnExceptionNumber != null)
    })) if(messagePayload.fs#Output.fs#Responses.fs#ResponseBase.fs#Errors.*fs#Error != null),
	'userAuthentication': messagePayload.fs#Output.*fs#UserAuthentication map ((item, index) -> {
    	'wasSuccessful': item.WasSuccessful as Boolean,
    	('errors': item.Errors.*Error map ((item,index)->{
    		'errorMessage': item.ErrorMessage,
    		'errorNumber': item.ErrorNumber as Number,
    		'oraErrorMessage': item.OraErrorMessage,
    		('rtxnExceptionMessage': item.RtxnExceptionMessage) if(item.RtxnExceptionMessage != null),
    		('rtxnExceptionNumber': item.RtxnExceptionNumber) if(item.RtxnExceptionNumber != null)
    	})) if(item.Errors.*Error != null)
	})
}